[project]
name = "marketfeed"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Edward Simpson-Fitzgibbon", email = "edward.psf@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
marketfeed = "marketfeed:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
